#!/bin/bash
# Script to remove duplicate registry and inventory files
# Generated by duplicate_analysis.py

set -e

# Group: ⭣_memory_registry_initializer__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/⭣_memory_registry_initializer__IN__20250527_005618.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/⭣_memory_registry_initializer__IN__20250527_005618.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/⭣_memory_registry_initializer__IN__20250527_005618.json.bak"

# Group: registry_index.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/registry_index.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/registry_index.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/registry_index.json.bak"
rm "/Users/jbear/FIELD/⭣_registry/_core/registry_index.json.bak"

# Group: R11_architecture_snapshot_updated_20250421.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⬠_cognitive_expression/🜛_mind/R11_architecture_snapshot_updated_20250421.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/R11_architecture_snapshot_updated_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/R11_architecture_snapshot_updated_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/R11_architecture_snapshot_updated_20250421.json.bak"

# Group: walker_registry_beacon.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/walker_registry_beacon.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/walker_registry_beacon.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/walker_registry_beacon.json.bak"
rm "/Users/jbear/FIELD/◼︎DOJO/◉_walkers/walker_registry_beacon.json.bak"

# Group: ⭣_memory_update_registry__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/⭣_memory_update_registry__IN__20250527_005614.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/⭣_memory_update_registry__IN__20250527_005614.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/⭣_memory_update_registry__IN__20250527_005614.json.bak"

# Group: ●_router_tata_registry_copy__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/●_router_tata_registry_copy__IN__20250527_010118.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/●_router_tata_registry_copy__IN__20250527_010118.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/●_router_tata_registry_copy__IN__20250527_010118.json.bak"

# Group: obi-wan_optimized_registry.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⭣_registry/obi-wan_optimized_registry.json.bak
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000508/reflective/obi-wan_optimized_registry.json.bak"
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000559/reflective/obi-wan_optimized_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/obi-wan_optimized_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/obi-wan_optimized_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/obi-wan_optimized_registry.json.bak"

# Group: cloud_inventory.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/cloud_inventory_20250628_185116.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/cloud_inventory_20250628_185116.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/cloud_inventory_20250628_185116.json.bak"

# Group: ⦿_registry.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/⦿_registry.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/⦿_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/⦿_registry.json.bak"

# Group: ●_router__icloud_structure_snapshot__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/●_router__icloud_structure_snapshot__IN__20250527_005923.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/●_router__icloud_structure_snapshot__IN__20250527_005923.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/●_router__icloud_structure_snapshot__IN__20250527_005923.json.bak"

# Group: registry.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/registry.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/registry.json.bak"

# Group: ⦿_registry_coordination.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/⦿_registry_coordination.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/⦿_registry_coordination.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/⦿_registry_coordination.json.bak"

# Group: demo_inventory.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/demo_inventory_20250628_184155.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/demo_inventory_20250628_184155.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/demo_inventory_20250628_184155.json.bak"

# Group: placeholder_registry_report.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/placeholder_registry_report.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/placeholder_registry_report.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/placeholder_registry_report.json.bak"

# Group: ⭣_memory_tata_registry__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/⭣_memory_tata_registry__IN__20250527_010115.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/⭣_memory_tata_registry__IN__20250527_010115.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/⭣_memory_tata_registry__IN__20250527_010115.json.bak"

# Group: obiwan_registry.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⭣_registry/obiwan_registry.json.bak
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000508/reflective/obiwan_registry.json.bak"
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000559/reflective/obiwan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/obiwan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/obiwan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/obiwan_registry.json.bak"

# Group: device_field_registry.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/device_field_registry.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/device_field_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/device_field_registry.json.bak"

# Group: ●_router_tata_optimized_registry__IN_.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/●_router_tata_optimized_registry__IN__20250527_010113.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/●_router_tata_optimized_registry__IN__20250527_010113.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/●_router_tata_optimized_registry__IN__20250527_010113.json.bak"

# Group: abi_registry.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/abi_registry.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/abi_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/abi_registry.json.bak"

# Group: ◎_canonical_elemental_registry.json.bak
# KEEPING: /Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/◎_canonical_elemental_registry.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/◎_canonical_elemental_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/◎_canonical_elemental_registry.json.bak"

# Group: R11_memory_snapshot_batch1_20250421.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⬠_cognitive_expression/🜛_mind/R11_memory_snapshot_batch1_20250421.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/R11_memory_snapshot_batch1_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/R11_memory_snapshot_batch1_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/R11_memory_snapshot_batch1_20250421.json.bak"

# Group: obi-wan_registry copy.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⭣_registry/obi-wan_registry copy.json.bak
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000508/reflective/obi-wan_registry copy.json.bak"
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000559/reflective/obi-wan_registry copy.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/obi-wan_registry copy.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/obi-wan_registry copy.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/obi-wan_registry copy.json.bak"

# Group: obi-wan_registry.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⭣_registry/obi-wan_registry.json.bak
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000508/reflective/obi-wan_registry.json.bak"
rm "/Users/jbear/FIELD/●OBI-WAN/📁_archive_or_general_assets/reflective_backup_20250602_000559/reflective/obi-wan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/obi-wan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/obi-wan_registry.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/obi-wan_registry.json.bak"

# Group: R11_architecture_snapshot_20250421.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⬠_cognitive_expression/🜛_mind/R11_architecture_snapshot_20250421.json.bak
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_023241/R11_architecture_snapshot_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_011356/R11_architecture_snapshot_20250421.json.bak"
rm "/Users/jbear/FIELD/◇_port_migration_backup_20250629_002053/R11_architecture_snapshot_20250421.json.bak"

# Group: sacred_field_state.json.bak
# KEEPING: /Users/jbear/FIELD/●OBI-WAN/⭣_registry/sacred_field_states/sacred_field_state_2025-06-17T21-30-53-768585.json.bak
rm "/Users/jbear/FIELD/●OBI-WAN/⭣_registry/sacred_field_state.json.bak"

