#!/bin/bash
# Monitor Sacred NixOS Deployment

echo "═══════════════════════════════════════════════════════════════"
echo "     MONITORING SACRED NIXOS DEPLOYMENT     "
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "To execute the deployment on nixos-kitchen:"
echo ""
echo "1. SSH into the system:"
echo "   ssh jb@nixos-kitchen"
echo ""
echo "2. Run the deployment script:"
echo "   ./sacred-deploy-full.sh"
echo ""
echo "3. Type 'SACRED' when prompted to confirm"
echo ""
echo "The script will:"
echo "  ✓ Completely wipe /dev/sda (1TB Fusion drive)"
echo "  ✓ Create new partitions (Boot, Root, Swap, Sacred)"
echo "  ✓ Install NixOS with the Sacred 9 Chakra configuration"
echo "  ✓ Set up all dimensional gateway services"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Current disk status on nixos-kitchen:"
ssh jb@nixos-kitchen "lsblk /dev/sda && echo '' && df -h | grep -E '(Filesystem|sda|nvme)'"
